---
title: "StarSchema"
author: "Andrew Lowe"
date: "8 January 2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in the data (and drop the numeric data to save RAM):
```{r}
require(readr)
# dat <- fread("C:/Work/Projects/Bayer/ws/Tableau/_work/output/StarSchema_CAT_PT_OVR.csv",
#                     select = c(2, 8, 9, 36, 38, 46, 50, 54, 58, 59, 63, 197), 
#                     showProgress = T)
```

```{r}
dat <- read_csv("C:/Work/Projects/Bayer/ws/Tableau/_work/output/GoldenStandardAddressable.csv")
```

```{r}
include.rows <- with(dat,
                     (SOURCE_CODE == "OTC_PEC") & 
                       (MARKET_LEVEL == "TOTAL") & 
                       (IS_CATEGORY_MAPPED == "YES" | IS_CATEGORY_MAPPED == "Y") & 
                       (
                         (Distribution_ChainDescription == "Pharmacies") | 
                           (Distribution_Channel_Name == "Pharmacies")
                       ) &
                       !is.na(Month) &
                       Prescription_Type == "Sans Prescription"
)

dat <- dat[include.rows,]
```

```{r}
require(dplyr)
dat %>% 
  group_by(PHARMA_BRAND) %>% 
  count() %>% 
  head()
```

```{r}
require(ggplot2)
dat %>% 
  arrange(Month) %>% 
  group_by(PHARMA_BRAND, Month) %>% 
  summarise(Total = sum(Sellout_TurnoverBRG)) %>% 
  ggplot(aes(x = Month, y = Total, colour = PHARMA_BRAND)) +
  geom_point() +
  geom_line()
```

```{r}
dat %>% 
  arrange(Month) %>% 
  group_by(PHARMA_GROUP, Month) %>% 
  summarise(Total = sum(Sellout_TurnoverBRG)) %>% 
  ggplot(aes(x = Month, y = Total, colour = PHARMA_GROUP)) +
  geom_point() +
  geom_line()
```

```{r}
dat %>% 
  arrange(Month) %>% 
  group_by(PHARMA_GROUP, Month) %>% 
  summarise(Total = sum(Sellout_TurnoverBRG)) %>%
  filter(PHARMA_GROUP == "BAYER CC") %>% 
  ggplot(aes(x = Month, y = Total, colour = PHARMA_GROUP)) +
  geom_point() +
  geom_line()
```

```{r}
require(prophet)
dat %>% 
  arrange(Month) %>% 
  group_by(PHARMA_GROUP, Month) %>% 
  summarise(Total = sum(Sellout_TurnoverBRG)) %>% 
  filter(PHARMA_GROUP == "BAYER CC") -> product

df <- product[c("Month", "Total")]
names(df) <- c("ds","y")

m <- prophet(df)
```

```{r}
future <- make_future_dataframe(m, periods = 12, freq = "month")
head(future)
```

```{r}
forecast <- predict(m, future)
head(forecast)
```

```{r}
plot(m, forecast)
prophet_plot_components(m, forecast)
```
```{r}
require(forecast)
temp <- ts(df$y, frequency = 12, start = c(2014, 7))
fit <- auto.arima(temp, trace = TRUE)
fit
arima.forecast <- forecast(fit, h = 12)
plot(arima.forecast)
arima.forecast
```

```{r}
acf(df$y)
pacf(df$y)
```

```{r}
knitr::knit_exit()
```


```{r, cache=T}
StarSchema$IS_CATEGORY_MAPPED <- factor(StarSchema$IS_CATEGORY_MAPPED)
StarSchema$MARKET_LEVEL <- factor(StarSchema$MARKET_LEVEL)
StarSchema$SOURCE_CODE <- factor(StarSchema$SOURCE_CODE)
StarSchema$Month <- factor(StarSchema$Month == "")
StarSchema$Distribution_ChainDescription <- factor(StarSchema$Distribution_ChainDescription)
StarSchema$Distribution_Channel_Name <- factor(StarSchema$Distribution_Channel_Name)
```

```{r, cache=T}
table(StarSchema$IS_CATEGORY_MAPPED)/sum(table(StarSchema$IS_CATEGORY_MAPPED))*100
table(StarSchema$MARKET_LEVEL)/sum(table(StarSchema$MARKET_LEVEL))*100
table(StarSchema$SOURCE_CODE)/sum(table(StarSchema$SOURCE_CODE))*100
table(StarSchema$Month)/sum(table(StarSchema$Month))*100
table(StarSchema$Distribution_ChainDescription)/sum(table(StarSchema$Distribution_ChainDescription))*100
table(StarSchema$Distribution_Channel_Name)/sum(table(StarSchema$Distribution_Channel_Name))*100
```

```{r, cache=T}
pie(table(StarSchema$IS_CATEGORY_MAPPED))
pie(table(StarSchema$MARKET_LEVEL))
pie(table(StarSchema$SOURCE_CODE))
pie(table(StarSchema$Month))
pie(table(StarSchema$Distribution_ChainDescription))
pie(table(StarSchema$Distribution_Channel_Name))
```

